export {
  LnBot,
  WalletsResource,
  KeysResource,
  InvoicesResource,
  PaymentsResource,
  AddressesResource,
  TransactionsResource,
  WebhooksResource,
  EventsResource,
  BackupResource,
  RestoreResource,
} from "./client.js";

export { LnBotError, BadRequestError, NotFoundError, ConflictError } from "./errors.js";

export type {
  LnBotConfig,
  InvoiceStatus,
  PaymentStatus,
  TransactionType,
  WalletResponse,
  CreateWalletRequest,
  CreateWalletResponse,
  UpdateWalletRequest,
  ApiKeyResponse,
  RotateApiKeyResponse,
  CreateInvoiceRequest,
  CreateInvoiceForWalletRequest,
  CreateInvoiceForAddressRequest,
  AddressInvoiceResponse,
  InvoiceResponse,
  ListInvoicesParams,
  CreatePaymentRequest,
  PaymentResponse,
  ListPaymentsParams,
  CreateAddressRequest,
  AddressResponse,
  TransferAddressRequest,
  TransferAddressResponse,
  TransactionResponse,
  ListTransactionsParams,
  CreateWebhookRequest,
  CreateWebhookResponse,
  WebhookResponse,
  RecoveryBackupResponse,
  RecoveryRestoreRequest,
  RecoveryRestoreResponse,
  BackupPasskeyBeginResponse,
  BackupPasskeyCompleteRequest,
  RestorePasskeyBeginResponse,
  RestorePasskeyCompleteRequest,
  RestorePasskeyCompleteResponse,
  InvoiceEvent,
  PaymentEvent,
  WalletEvent,
  WalletEventType,
  CredentialCreateOptions,
  AssertionOptions,
  AuthenticatorAttestationRawResponse,
  AuthenticatorAssertionRawResponse,
} from "./types.js";
